CREATE TABLE [dbo].[Orders]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY , 
    [UserId] NVARCHAR(128) NOT NULL, 
    [DeviceId] INT NOT NULL, 
    [Price] FLOAT NULL,
	FOREIGN KEY (UserId) REFERENCES AspNetUsers(Id) ON DELETE CASCADE,
	FOREIGN KEY (DeviceId) REFERENCES Devices(Id) ON DELETE CASCADE
)
