CREATE TABLE [dbo].[Task_Part]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [TaskId] INT NOT NULL, 
    [PartId] INT NOT NULL,
	FOREIGN KEY (TaskId) REFERENCES TaskProgress(Id) ON DELETE CASCADE,
	FOREIGN KEY (PartId) REFERENCES Parts(Id) ON DELETE CASCADE,
)
