//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Part
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int PartId { get; set; }
    
        public virtual Parts Parts { get; set; }
        public virtual TaskProgress TaskProgress { get; set; }
    }
}
